# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentpane < Formula
  desc "Tmux-based long-running task orchestration for AI agents"
  homepage "https://github.com/darshan-rambhia/tmux-agentpane"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darshan-rambhia/tmux-agentpane/releases/download/v0.1.0/tmux-agentpane_0.1.0_darwin_amd64.tar.gz"
      sha256 "8051b607cdec24baa7910bb16b9b51d5ba73ee680251b5102563635374284922"

      def install
        bin.install "agentpane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darshan-rambhia/tmux-agentpane/releases/download/v0.1.0/tmux-agentpane_0.1.0_darwin_arm64.tar.gz"
      sha256 "ff54dcddc29940a118487230dfa1cd6ff5f54b44fe34bdf990c9139d01e9f58e"

      def install
        bin.install "agentpane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darshan-rambhia/tmux-agentpane/releases/download/v0.1.0/tmux-agentpane_0.1.0_linux_amd64.tar.gz"
      sha256 "0627bd39e7a975435b078bc4d2a52ec527fbb7b3bab8fb63fbd766542eaac8b8"
      def install
        bin.install "agentpane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darshan-rambhia/tmux-agentpane/releases/download/v0.1.0/tmux-agentpane_0.1.0_linux_arm64.tar.gz"
      sha256 "bd13299b7d2aaf924a6808e3f00e0e516f7a05f3a34c24c68d27aedef42c0018"
      def install
        bin.install "agentpane"
      end
    end
  end

  test do
    system "#{bin}/agentpane", "--help"
  end
end
