# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glint < Formula
  desc "Lightweight Proxmox monitoring dashboard"
  homepage "https://github.com/darshan-rambhia/glint"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darshan-rambhia/glint/releases/download/v0.1.0/glint_0.1.0_darwin_amd64.tar.gz"
      sha256 "91930134f221296ba715c987c3202d5c2992fb69ede874c8f128f12c708eacbf"

      def install
        bin.install "glint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darshan-rambhia/glint/releases/download/v0.1.0/glint_0.1.0_darwin_arm64.tar.gz"
      sha256 "627976a4babcb505af7123d0796660aacb13a259b394fe37b89fca51a040c35c"

      def install
        bin.install "glint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darshan-rambhia/glint/releases/download/v0.1.0/glint_0.1.0_linux_amd64.tar.gz"
      sha256 "ce58cc3c91c299eced6edf14d4514a9c893dd191e785935317c242b710b0731a"
      def install
        bin.install "glint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darshan-rambhia/glint/releases/download/v0.1.0/glint_0.1.0_linux_arm64.tar.gz"
      sha256 "55c64a0cd2747ca58748ec96e447e6dae9238392d7370c3de8a45cebdfc12330"
      def install
        bin.install "glint"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glint --version")
  end
end
