# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glint < Formula
  desc "Lightweight Proxmox monitoring dashboard"
  homepage "https://github.com/darshan-rambhia/glint"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/darshan-rambhia/glint/releases/download/v0.2.0/glint_0.2.0_darwin_amd64.tar.gz"
      sha256 "9a9e0be7205ac89d74a7ac36cce1ac157909032fa7e866b962bfa4d4fe9c3689"

      def install
        bin.install "glint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/darshan-rambhia/glint/releases/download/v0.2.0/glint_0.2.0_darwin_arm64.tar.gz"
      sha256 "396994444b8fedd6e8b95fcdfac98823d6cf710ac0bd30e1a20fce7af710cf63"

      def install
        bin.install "glint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/darshan-rambhia/glint/releases/download/v0.2.0/glint_0.2.0_linux_amd64.tar.gz"
      sha256 "9d18f7283e34036488d711065f625a0a675f6bbfa65c30f220dbb6f8bb419fea"
      def install
        bin.install "glint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/darshan-rambhia/glint/releases/download/v0.2.0/glint_0.2.0_linux_arm64.tar.gz"
      sha256 "77b3821e843ef80a25e1cbb768633f038ae345d8d7f53323fe8ef42088622674"
      def install
        bin.install "glint"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/glint --version")
  end
end
